name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - phase-1/week-2/day-7-cicd-advanced
  pull_request:
    branches:
      - main
      - phase-1/week-2/day-7-cicd-advanced
permissions:
  contents: read
  packages: write
  security-events: write

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

  test:
    name: Test (Node ${{ matrix.node }} - ${{ matrix.os }})
    needs: lint
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node: [18, 20, 22]
        os:
          - ubuntu-22.04
          - ubuntu-24.04
        exclude:
          - node: 18
            os: ubuntu-24.04

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run unit test
        run: npm test
     
  build-and-push:
    needs: [lint, test]
    if: github.event_name == 'push'
    uses: ./.github/workflows/reusable-build.yml
    with:
      image_name: demo-app
      image_tag: sha-${{ github.sha }}
    secrets:
      registry_password: ${{ secrets.GITHUB_TOKEN }}
