name: CI Pipeline

on:
  push:
    branches:
      - main
      - phase-1/week-2/day-7-cicd-advanced
  pull_request:
    branches:
      - main
      - phase-1/week-2/day-7-cicd-advanced
permissions:
  contents: read
  packages: write
  security-events: write

jobs:
  lint:
    name: Lint Source
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

  test:
    name: Run Unit Tests
    needs: lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Execute tests
        run: npm test
  build-image:
    name: Build Docker Image
    needs: test

    if: github.event_name == 'push' &&
        github.ref == 'refs/heads/main'

    uses: ./.github/workflows/reusable-build.yml

    with:
      image_name: demo-app
      image_tag: latest

    secrets: inherit
    
  trivy-scan:
    needs: build-image

    runs-on: ubuntu-latest

    steps:
      - uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/${{ needs.build-image.outputs.owner }}/demo-app:sha-${{ needs.build-image.outputs.short_sha }}
          format: table
          exit-code: 0
          severity: HIGH,CRITICAL
          
  generate-sbom:
    name: Generate SBOM
    needs: [trivy-scan, build-image]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          image: ghcr.io/${{ needs.build-image.outputs.owner }}/demo-app:sha-${{ needs.build-image.outputs.short_sha }}
          format: spdx-json
          output-file: sbom.spdx.json

      - name: Upload SBOM Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.spdx.json
